---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfsecurity/scantron-scan
    tag: latest

inputs:
- name: scantron
- name: scantron-binary

outputs:
- name: scantron-reports

run:
  path: docker/scan.sh

params:
  BOSH_ADDRESS:
  BOSH_CLIENT_ID:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
  BOSH_DEPLOYMENT:
